name: main

on:
  push:
    # branches:
    #   - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: echo '//npm.pkg.github.com/:_authToken=$NPM_TOKEN' > ~/.npmrc
      - run: yarn install
      - run: yarn release
